# Define your dev environment
FROM node:12-stretch

# install and dev dependencies
RUN npm install --global eslint prettier

# devcontainer.json lists container metadata
# open just 8-vsCodeContainer in its own vscode window (with remote container extension) to get prompt to open in container